language: node_js
node_js:
  - "8.10.0"
services:
  - postgresql
addons:
  postgresql: "9.4"
cache:
  directories:
    - "node_modules"
  yarn: true
before_install:
  - psql -c 'create database test;' -U postgres
install:
  - yarn install
  - yarn dbsetup:test
before_script:
  - yarn start:testdb &
script:
  - yarn test
  - yarn cy:run
after_script:
  - yarn dbtakedown:test