export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CHAT_WORKFLOWS_LOAD = 'CHAT_WORKFLOWS_LOAD';
export const CHAT_WORKFLOW_CHANGE = 'CHAT_WORKFLOW_CHANGE';

export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_CLEAR_ALL = 'MESSAGE_CLEAR_ALL';
